-- Drop ONE OptionContractTick index that has never been read.
--
-- Across 11 boot sessions (2026-08-08 .. 2026-08-19, from
-- ops/scripts/capture-index-usage.sh) this index recorded 0 reads, 0 writes
-- and 0 deletes. It is the [underlyingSymbol, expiryLabel, optionType,
-- strikePrice, tickTime] composite with tradingDate spliced into position 3,
-- so anything it could serve is served by that composite's prefix - EXPLAIN
-- on the hot getLatestLegTick query lists it as a candidate and the optimiser
-- rejects it in favour of the composite with a backward scan.
--
-- Two SIBLING indexes were nearly dropped alongside it and must NOT be:
--   [tickTime]                        179,383,660 reads across the same 11 sessions
--   [tradingDate, underlyingSymbol,…]  37,205,418 reads
-- Both showed 0 reads on the single day first examined. performance_schema
-- resets on every MySQL restart and this host stops nightly, so a live counter
-- can never see past the morning boot. Read the capture report, not the live
-- counters. The tradingDate index additionally backs
-- scripts/sync-prod-db.sh's `mysqldump --where='tradingDate="$day"'`.
--
-- NOTE ON DISK: with innodb_file_per_table these pages return to the
-- tablespace free list, not the OS - the .ibd does not shrink without an
-- OPTIMIZE TABLE rebuild, deliberately not done here (91M rows, ~20GB temp).

-- DropIndex
DROP INDEX `OptionContractTick_underlyingSymbol_expiryLabel_tradingDate__idx` ON `OptionContractTick`;
