-- AlterTable
ALTER TABLE `SimTrade` MODIFY `strategyType` ENUM('SHORT_STRADDLE', 'BULL_PUT_SPREAD', 'BEAR_CALL_SPREAD', 'IRON_CONDOR', 'NAKED_CALL', 'NAKED_PUT', 'SHORT_STRANGLE', 'IRON_BUTTERFLY') NOT NULL;
